pull_request_rules:
  - name: Automatic merge on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/push
    actions:
      merge:
        method: merge
      delete_head_branch:
